services:
  - type: web
    name: erp-club-backend
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: "20"
