services:
  - type: web
    name: erp-club-backend
    runtime: node
    buildCommand: npm install && npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: CORS_ALLOW_LOCALHOST
        value: "true"
